
include: "rules/common.smk"
include: "rules/repeats.smk"
include: "rules/transcriptome_using_genome.smk"
include: "rules/transcriptome_de_novo.smk"
include: "rules/consensus_transcriptome.smk"
include: "rules/gene_pred.smk"
# include: "rules/gene_filter.smk"
include: "rules/filter_repeats.smk"
include: "rules/gene_annot.smk"

# "results/pfam/unfiltered.genes.pfam-domains.txt", "results/pfam/.end"

rule all:
    input:  "results/pasa/pasa_gene_models.gff3"#"results/filter_models/genes.svg", "results/filter_models/pfam.svg", "results/filter_models/busco.svg"#"results/pfam/.end"#"results/filter_models/longest_isoform.gff", #"results/pasa/.end"
             #expand("results/filter_models/gene_models.filt.{i}.gff3", i=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
