
include: "rules/common.smk"
include: "rules/repeats.smk"
include: "rules/transcriptome_using_genome.smk"
include: "rules/transcriptome_de_novo.smk"
#include: "rules/gene_pred.smk"

rule all:
    input: f'results/repeats/{GENOME}_repeat_landscape.html', 'results/trinity_mapped/Trinity_transcripts.gff3', "results/portcullis/3-filt/portcullis_filtered.pass.junctions.bed"
     