
genome: "resources/amphiura_scaf1_subset.fa"
rna_samples: "config/samples.tsv"

transdecoder_predict_args: "--no_refine_starts"
diamond: "home/elise/projects/annot/AnnotateSnakeMake/resources/swissprot.metazoa.dmnd"
