# Required arguments, this example config runs the test example

## Input data: rna samples (fastqs, listed in a 'tsv' file) and the fasta of the genome
rna_samples: "config/samples.tsv"
genome: "resources/afil_subset_scaf20.fa"

## Configuration files for some of the pipeline's tools (see provided examples)
mikado: "config/mikado.conf" 
augustus_config: "config/augustus_extrinsic.E.W.P.cfg"

## Protein databases for gene annontation and gene naming
diamond: "resources/swissprot.metazoa.dmnd"
prot_fasta: "resources/metaeuk/prot.fa"

## Pfam database for dmain annotation
pfam_db: "resources/pfam_db/Pfam-A.hmm.h3i"

#-------------------------------------------------------------------------------------------------#

# Optional, additional arguments for transdecoder (suggest removing, only for speed of test run)
transdecoder_predict_args: "--no_refine_starts"